id = "m-ayane-screen-test-c835db0e50"
title = "Ayane Screen Test"
tag = "EARL"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/earl/Ayane Screen Test.mov"
cache = true
