id = "m-drumdrops-screen-test-8fa37ef647"
title = "Drumdrops Screen Test"
tag = "EARL"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/earl/Drumdrops Screen Test.mov"
cache = true
