id = "m-secret-life-of-drake-mallard-2b6a194fd1"
title = "Secret Life of Drake Mallard"
subtitle = "Loop"
tag = "FILM"

[source]
type = "path"
value = "/Volumes/share/mars_films/2025/FILM_FESTIVAL/secret life of drake mallard.mp4"
