id = "pl-mallard-mystery"
name = "Mallard Mystery playlist"

[[item]]
media = "m-secret-life-of-drake-mallard-2b6a194fd1"
duration_slots = 2
title = "Secret Life of Drake Mallard"
subtitle = "Loop"
tag = "FILM"
