id = "pl-chebel-a"
name = "Chebel playlist A"

[[item]]
media = "m-eden-698e39ecb02116113cd3d0f7"
duration_slots = 1
title = "hologram spirit: composition made up of glowing binary code, symbolizing the merging of human emotion and technology, incredible digital art, cyberpunk, neon colors, glitch effects, 3D octane render, HD"
tag = "CHEBEL"

[[item]]
media = "m-eden-698e341c5ccc27be2922f835"
duration_slots = 1
title = "fireflies in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-698e33d95ccc27be2922f831"
duration_slots = 1
title = "fireflies in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-6814eba0e2492713918ede6f"
duration_slots = 1
title = "crystals, blue feathers, prisms, rainbows, wood, at night, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-6814eb5be2492713918ede6c"
duration_slots = 1
title = "jungle at night, black background, crystals, blue feathers, prisms, rainbows, wood, at night, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-6814eb1de2492713918ede6a"
duration_slots = 1
title = "crystals, blue feathers, prisms, rainbows, wood, at night, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-6814e8af0d08f6a7eae75674"
duration_slots = 1
title = "dense jungle, foliage, nature, mystical amazon forest at night, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-67dafa4cdbe6528fa17b34ae"
duration_slots = 1
title = "giant heads, huge sculptures of a head in a field by the moonlight, full moon in the sky, stars, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-67dafa39dbe6528fa17b34ac"
duration_slots = 1
title = "giant heads, huge sculptures of a head in a field by the moonlight, full moon in the sky, stars, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-67ccc1c7e7712a0d8bce3882"
duration_slots = 1
title = "this is a tbd side task"
tag = "CHEBEL"

[[item]]
media = "m-eden-67cbde4f867fc6d4af22ea76"
duration_slots = 1
title = "this is a tbd side task"
tag = "CHEBEL"

[[item]]
media = "m-eden-67cbde3602bcc2685a2103c9"
duration_slots = 1
title = "this is a tbd side task"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04e94470902c33f66029d"
duration_slots = 1
title = "Plum Blossom"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04ca6470902c33f61a28c"
duration_slots = 1
title = "a chinese dragon in the sky"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04b42470902c33f5e8a3b"
duration_slots = 1
title = "tea ceremony, asian art"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e0497a470902c33f5d56f8"
duration_slots = 1
title = "close up of a water fountain, a bucket and a laddle, asian art"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e048f9470902c33f5cd01b"
duration_slots = 1
title = "close up of a water fountain, a bucket and a laddle, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e048c5470902c33f5c9b73"
duration_slots = 1
title = "mist, fog, misty mountain, mysterious foggy mountain, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04851470902c33f5bb944"
duration_slots = 1
title = "mist, fog, misty mountains, mysterious foggy hills, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e0483b470902c33f5b7519"
duration_slots = 1
title = "mist, fog, misty mountains, mysterious foggy hills, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e0481e470902c33f5b395d"
duration_slots = 1
title = "misty mountains, mysterious foggy hills, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e047d9470902c33f5a898f"
duration_slots = 1
title = "mazu the taiwanese goddess of the ocean, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e047bd470902c33f5a56fa"
duration_slots = 1
title = "mazu the taiwanese goddess of the ocean, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04721470902c33f5942d2"
duration_slots = 1
title = "the waves in the ocean breaking on the shore, sea of stars, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04712470902c33f5929c3"
duration_slots = 1
title = "the waves in the ocean breaking on the shore, sea of stars, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e0470b470902c33f5913d9"
duration_slots = 1
title = "the waves in the ocean breaking on the shore, sea of stars, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e046fd470902c33f58f47e"
duration_slots = 1
title = "the waves in the ocean breaking on the shore, sea of stars, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e046ef470902c33f58e1af"
duration_slots = 1
title = "the waves in the ocean breaking on the shore, sea of stars, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e046c2470902c33f58ad61"
duration_slots = 1
title = "a beautiful waterfall surrounded by blooming flowers and butterflies, sunrise, colors of dawn, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e046b5470902c33f589455"
duration_slots = 1
title = "a beautiful waterfall surrounded by blooming flowers and butterflies, sunrise, colors of dawn, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e046a6470902c33f58750a"
duration_slots = 1
title = "a beautiful waterfall surrounded by blooming flowers and butterflies, sunrise, colors of dawn, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04689470902c33f584c42"
duration_slots = 1
title = "a beautiful waterfall surrounded by flowers and butterflies, sunrise, colors of dawn, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e0465e470902c33f581752"
duration_slots = 1
title = "a beautiful lake reflecting the stars at night, calm waters, a boat and a thatched hut lit in the distance, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04651470902c33f580159"
duration_slots = 1
title = "a beautiful lake reflecting the stars at night, calm waters, a boat and a thatched hut lit in the distance, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e0463e470902c33f57e84d"
duration_slots = 1
title = "a beautiful lake reflecting the stars at night, calm waters, a boat and a thatched hut lit in the distance, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04625470902c33f57d232"
duration_slots = 1
title = "a beautiful lake reflecting the stars at night, calm waters, a boa and a thatched hut lit in the distance, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e0461e470902c33f57b927"
duration_slots = 1
title = "a beautiful lake reflecting the stars at night, calm waters, a boa and a thatched hut lit in the distance, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66e04617470902c33f57afae"
duration_slots = 1
title = "a beautiful lake reflecting the stars at night, calm waters, a boa and a thatched hut lit in the distance, asian art, painting, chinese, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66df762781c18004b759b297"
duration_slots = 1
title = "Waves of doubt and trust, Purpose unfolds with each step, Roots deep, paths revealed, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d67276dc291e57fb54e730"
duration_slots = 1
title = "Gentle autumn breeze, leaves dance upon the still pond, nature's soft whisper, visionary painting, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d671e4dc291e57fb547c5f"
duration_slots = 1
title = "a lettering in painted letters with the title \"CHEBEL\" in colorful paint painted by cuno amiet in black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d66ea8dc291e57fb518597"
duration_slots = 1
title = "A winding stone path, black background, moss clings to ancient footsteps, mist weaves through the trees. visionary painting, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d66dc1dc291e57fb512891"
duration_slots = 1
title = "A winding stone path, black background, moss clings to ancient footsteps, mist weaves through the trees. visionary painting, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d66a5fdc291e57fb503d27"
duration_slots = 1
title = "A winding stone path, black background, moss clings to ancient footsteps, mist weaves through the trees. visionary painting, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d6692cdc291e57fb4f5fab"
duration_slots = 1
title = "A tranquil pond rests, lotus blooms float like bright stars— reflections shimmer. asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d66916dc291e57fb4f44a7"
duration_slots = 1
title = "A tranquil pond rests, lotus blooms float like bright stars— reflections shimmer. psychedelic, visionary painting, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d668c4dc291e57fb4ed658"
duration_slots = 1
title = "A tranquil pond rests, lotus blooms float like bright stars— reflections shimmer. psychedelic, visionary painting, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d668b6dc291e57fb4ecff2"
duration_slots = 1
title = "A tranquil pond rests, lotus blooms float like bright stars— reflections shimmer. psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d66872dc291e57fb4e7e0a"
duration_slots = 1
title = "A lone cherry tree, blossoms cascade like pink rain— petals carpet ground. asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d66848dc291e57fb4e48a0"
duration_slots = 1
title = "A lone cherry tree, blossoms cascade like pink rain— petals carpet ground. visionary art, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d6680fdc291e57fb4e11db"
duration_slots = 1
title = "A lone cherry tree, blossoms cascade like pink rain— petals carpet ground. visionary art, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d667f4dc291e57fb4de462"
duration_slots = 1
title = "Moonlight on water, ripples weave a silver path— night's serene embrace. visionary art, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d667d9dc291e57fb4dd445"
duration_slots = 1
title = "Moonlight on water, ripples weave a silver path— night's serene embrace. asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d66793dc291e57fb4d9958"
duration_slots = 1
title = "Moonlight on water, ripples weave a silver path— night's serene embrace. psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d66670dc291e57fb4c8d4b"
duration_slots = 1
title = "steam rises gently, fragrant leaves unfurl and dance, time slows, peace descends, in the style of <concept>, visionary painting, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d6663adc291e57fb4c595e"
duration_slots = 1
title = "steam rises gently, fragrant leaves unfurl and dance, time slows, peace descends, in the style of <concept>, visionary painting, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d665f9dc291e57fb4c2964"
duration_slots = 1
title = "Lanterns softly glow, shadows play on paper walls, tea warms the still night, in the style of <concept>, visionary painting, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d665cfdc291e57fb4c0fee"
duration_slots = 1
title = "Lanterns softly glow, shadows play on paper walls, tea warms the still night, in the style of <concept>, visionary painting, psychedelic, asian art, black background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d665b4dc291e57fb4be4a3"
duration_slots = 1
title = "Lanterns softly glow, shadows play on paper walls, tea warms the still night, in the style of <concept>, visionary painting, psychedelic, asian art"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d6658fdc291e57fb4bcb47"
duration_slots = 1
title = "Lanterns softly glow, shadows play on paper walls, tea warms the still night, in the style of <concept>, visionary painting, psychedelic, asian art"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d23af9479cd41e902c9ab3"
duration_slots = 1
title = "lonely fireflies landscape in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d23ad9479cd41e902c5037"
duration_slots = 1
title = "lonely fireflies landscape in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d23acb479cd41e902c407f"
duration_slots = 1
title = "lonely fireflies landscape in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d23ab9479cd41e902c2131"
duration_slots = 1
title = "lonely fireflies landscape in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d23aa9479cd41e902c0b26"
duration_slots = 1
title = "lonely fireflies landscape in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d23a86479cd41e902bf212"
duration_slots = 1
title = "fireflies in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d23a5b479cd41e902bc3a1"
duration_slots = 1
title = "fireflies in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d23a2f479cd41e902bb3b3"
duration_slots = 1
title = "fireflies in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66d238b6479cd41e902b6d7d"
duration_slots = 1
title = "fireflies in a dark background"
tag = "CHEBEL"

[[item]]
media = "m-eden-66c6322fcf36155ceb0a60ce"
duration_slots = 1
title = "Waves of doubt and trust, Purpose unfolds with each step, Roots deep, paths revealed."
tag = "CHEBEL"

[[item]]
media = "m-eden-66c631e0cf36155ceb0a437e"
duration_slots = 1
title = "Waves of doubt and trust, Purpose unfolds with each step, Roots deep, paths revealed."
tag = "CHEBEL"

[[item]]
media = "m-eden-66461e364a40c7cdc3c51eb3"
duration_slots = 1
title = "thai dancer"
tag = "CHEBEL"

[[item]]
media = "m-eden-66461e054a40c7cdc3c4c0a9"
duration_slots = 1
title = "kabuki mask"
tag = "CHEBEL"

[[item]]
media = "m-eden-66461dc84a40c7cdc3c478fc"
duration_slots = 1
title = "sichuan opera dancer"
tag = "CHEBEL"

[[item]]
media = "m-eden-66461daf4a40c7cdc3c44e5e"
duration_slots = 1
title = "buto dancer dressed all in white"
tag = "CHEBEL"

[[item]]
media = "m-eden-66461d354a40c7cdc3c3b7a8"
duration_slots = 1
title = "eyes pattern, many eyes, eye in the sky, eyes as stars"
tag = "CHEBEL"

[[item]]
media = "m-eden-66461cf51f76de1d6861ecd0"
duration_slots = 1
title = "eyes pattern, many eyes, eye in the sky, eyes as stars"
tag = "CHEBEL"

[[item]]
media = "m-eden-66461c121f76de1d686139e6"
duration_slots = 1
title = "starry night, empty forest"
tag = "CHEBEL"

[[item]]
media = "m-eden-66461be81f76de1d68611d94"
duration_slots = 1
title = "starry night, empty forest"
tag = "CHEBEL"

[[item]]
media = "m-eden-664619991f76de1d685f18df"
duration_slots = 1
title = "a volcano erupting at night"
tag = "CHEBEL"

[[item]]
media = "m-eden-664619441f76de1d685ec73a"
duration_slots = 1
title = "scary witch screaming onder the moon, dark night"
tag = "CHEBEL"

[[item]]
media = "m-eden-664618f01f76de1d685e855c"
duration_slots = 1
title = "a mermaid and a fairy under a rainbow, sunny day, flowers"
tag = "CHEBEL"

[[item]]
media = "m-eden-664618c11f76de1d685e6923"
duration_slots = 1
title = "witch doctor brewing potion at night, starry sky, mysterious vibes"
tag = "CHEBEL"

[[item]]
media = "m-eden-664618b51f76de1d685e6297"
duration_slots = 1
title = "witch doctor brewing potion at night, starry sky, mysterious vibes"
tag = "CHEBEL"

[[item]]
media = "m-eden-664618ad1f76de1d685e4cab"
duration_slots = 1
title = "witch doctor brewing potion at night, starry sky, mysterious vibes"
tag = "CHEBEL"

[[item]]
media = "m-eden-66458d601f76de1d682a8ea2"
duration_slots = 1
title = "women bathing in a waterfall"
tag = "CHEBEL"

[[item]]
media = "m-eden-66458ce21f76de1d6829f0cc"
duration_slots = 1
title = "a mountain landscape and a single tree being hit by a lightning bolt, thunderstorm"
tag = "CHEBEL"
