id = "pl-chebel-b"
name = "Chebel playlist B"

[[item]]
media = "m-eden-65cd1ff9b6124cd3122c5391"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman in the wind, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf30cb6124cd3121140fc"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf2b4b6124cd31210f9f8"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf2b4b6124cd31210f9f6"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf156b6124cd312103970"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf12fb6124cd312101de4"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf123b6124cd3120ff213"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf0edb6124cd3120f95ce"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf0b8b6124cd3120f41d4"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf082b6124cd3120f193a"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccf082b6124cd3120f1939"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccef9fb6124cd3120da632"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, women talking, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccef83b6124cd3120d72dd"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man and asian woman, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccef82b6124cd3120d6c56"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man working, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccee19b6124cd3120bd339"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man with unicycle, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccee19b6124cd3120bd338"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man with unicycle, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65cced45b6124cd3120b74f2"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man and woman around bonfire, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccecd4b6124cd3120b1dd7"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man with unicycle, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccecbeb6124cd3120b06aa"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man sitting holding a cup, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccec88b6124cd3120ac519"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, couple hugging, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccec88b6124cd3120ac517"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, couple hugging, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccec62b6124cd3120ab46c"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man looking at the horizon, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccec62b6124cd3120ab46b"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man looking at the horizon, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccec1db6124cd3120a9627"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, man looking at the horizon, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65ccea9ab6124cd31209ca30"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, boy wearing sunglasses, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65cce9c9b6124cd312091ef0"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, asian woman smiling, soft pastel sunset colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9ae96ca4d496037398179"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9ae90ca4d496037397789"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9ae82ca4d496037396048"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9ae4dca4d49603739044c"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9adf4ca4d49603738c4c9"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9adf4ca4d49603738c4c7"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9adbbca4d49603738a42a"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c982b9ca4d49603724d832"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c982b9ca4d49603724d82f"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c98213ca4d4960372447c6"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9820dca4d496037243a97"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9820dca4d496037243a95"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c98201ca4d49603724307a"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c981beca4d49603723f727"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c981beca4d49603723f726"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9623cca4d4960371a14c0"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c9623cca4d4960371a14bf"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c95ff2ca4d496037155934"
duration_slots = 1
title = "oil paint, brush strokes, mixed media, woman head from behind, soft pastel sunset colors colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c95ba5ca4d4960370c3a4f"
duration_slots = 1
title = "oil paint, friends, community, love, soft colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c95ba5ca4d4960370c3a4e"
duration_slots = 1
title = "oil paint, friends, community, love, soft colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c95b10ca4d4960370badf6"
duration_slots = 1
title = "oil paint, friends, community, love, soft colors"
tag = "CHEBEL"

[[item]]
media = "m-eden-65c95a0dca4d4960370a8411"
duration_slots = 1
title = "man driving bus, oil paint"
tag = "CHEBEL"
