id = "pl-earl"
name = "Earl playlist"

[[item]]
media = "m-ayane-screen-test-61c2f7f01b"
duration_slots = 1
title = "Ayane Screen Test"
tag = "EARL"

[[item]]
media = "m-bourbon-screen-test-aa49cf63b4"
duration_slots = 1
title = "Bourbon Screen Test"
tag = "EARL"

[[item]]
media = "m-compositestest-a8630d29cc"
duration_slots = 1
title = "CompositesTest"
tag = "EARL"

[[item]]
media = "m-drumdrops-screen-test-e0cbe3555d"
duration_slots = 1
title = "Drumdrops Screen Test"
tag = "EARL"

[[item]]
media = "m-full-band-screen-test-98065ba4b4"
duration_slots = 1
title = "Full Band Screen Test"
tag = "EARL"

[[item]]
media = "m-star-motion-graphics-b-roll-test-1829b26fa0"
duration_slots = 1
title = "Star motion graphics b roll test"
tag = "EARL"

[[item]]
media = "m-t-mort-screen-test-aa40df2c6a"
duration_slots = 1
title = "T Mort Screen Test"
tag = "EARL"

[[item]]
media = "m-wik-screen-test-b022567c1d"
duration_slots = 1
title = "Wik Screen Test"
tag = "EARL"
