id = "pl-ria"
name = "Snippets from Drawing Klerb"
title = "Snippets from Drawing Klerb"

artist = "Ria"

[[item]]
media = "m-drawing-klerb-excerpt-f6e285771d"
duration_slots = 1
title = "Drawing Klerb excerpt"
tag = "RIA"
