id = "pl-tarcila"
name = "Lepus Liturge Antology"
title = "Lepus Liturge Antology"

artist = "Tarcila"

[[item]]
media = "m-lepus-liturge-vii-5f442e7ddb"
duration_slots = 1
title = "Lepus Liturge VII"
tag = "TARCILA"
