[defaults]
user = "pi"
controller_url = "http://10.10.13.9:24422/"
guide_port = 5173
server_port = 8787

[defaults.nas]
host = "REPLACE_ME"
share = "share"
mount = "/Volumes/share"
user = "REPLACE_ME"
password = "REPLACE_ME"

[pis.upper-east-2]
host = "100.128.1.105"
password = "REPLACE_ME"
node_name = "upper-east-2"
api_key = "REPLACE_ME"
eden_key = "REPLACE_ME"
wifi_ssid = "REPLACE_ME"
wifi_password = "REPLACE_ME"

[pis.upper-east-2.nas]
user = "REPLACE_ME"
password = "REPLACE_ME"
