id = "m-007f18b8-f6af-44d2-b094-1e12832adee4-d3b9e1a760"
title = "007F18B8 F6AF 44D2 B094 1E12832ADEE4"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/007F18B8-F6AF-44D2-B094-1E12832ADEE4.jpg"
cache = true
