id = "m-0141d07f-b6c9-4213-a3cb-79ed1db0b0b2-122ec972b9"
title = "0141D07F B6C9 4213 A3CB 79ED1DB0B0B2"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/0141D07F-B6C9-4213-A3CB-79ED1DB0B0B2.jpg"
cache = true
