id = "m-05a0e200-dc70-4327-8ff2-d4e5fc22d49d-d4ad47479f"
title = "05A0E200 DC70 4327 8FF2 D4E5FC22D49D"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/05A0E200-DC70-4327-8FF2-D4E5FC22D49D.jpg"
cache = true
