id = "m-0a3a5406-64a7-477e-b4f8-6f14f6fdffed-5b5fb6e6c2"
title = "0A3A5406 64A7 477E B4F8 6F14F6FDFFED"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/0A3A5406-64A7-477E-B4F8-6F14F6FDFFED.jpg"
cache = true
