id = "m-151c9770-2ab7-48a7-bb3e-efc90cf351c5-19be53e81c"
title = "151C9770 2AB7 48A7 BB3E EFC90CF351C5"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/151C9770-2AB7-48A7-BB3E-EFC90CF351C5.jpg"
cache = true
