id = "m-18-img-8527-ca734e7596"
title = "18 IMG 8527"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/18_IMG_8527.jpg"
cache = true
