id = "m-2019-06-26-18-31-11-91a2bd530d"
title = "2019 06 26 18 31 11"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/2019-06-26 18-31-11.JPG"
cache = true
