id = "m-2022-04-04-161519-3-48b2a6f05c"
title = "2022 04 04 161519 3"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/2022-04-04 161519_3.png"
cache = true
