id = "m-20a38df9-5aa0-4143-bd0b-5aff7ac3c838-59a7895445"
title = "20A38DF9 5AA0 4143 BD0B 5AFF7AC3C838"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/20A38DF9-5AA0-4143-BD0B-5AFF7AC3C838.jpg"
cache = true
