id = "m-2017-6ed57bd4d1"
title = "Сигнализация леса    Варенъйе организм 2017"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/lyosha-signal-2017.mp4"
cache = true
