id = "m-3047b405-e9e6-4a8e-ae75-ec950c7fc67b-7b090f0a95"
title = "3047B405 E9E6 4A8E AE75 EC950C7FC67B"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/3047B405-E9E6-4A8E-AE75-EC950C7FC67B.jpg"
cache = true
