id = "m-39547bbd-daf9-4882-b4bc-552dfdbfd8b0-1489aea90b"
title = "39547BBD DAF9 4882 B4BC 552DFDBFD8B0"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/39547BBD-DAF9-4882-B4BC-552DFDBFD8B0.jpg"
cache = true
