id = "m-504364a6-26f1-4dc6-9d39-dbccde90aa5e-3087207ac3"
title = "504364A6 26F1 4DC6 9D39 DBCCDE90AA5E"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/504364A6-26F1-4DC6-9D39-DBCCDE90AA5E.jpg"
cache = true
