id = "m-59374ac8-7fc8-4262-9a0c-6f9ae36a7de8-b71ee9d292"
title = "59374AC8 7FC8 4262 9A0C 6F9AE36A7DE8"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/59374AC8-7FC8-4262-9A0C-6F9AE36A7DE8.jpg"
cache = true
