id = "m-6-million-dollar-duck-e89a6005d8"
title = "6 Million Dollar Duck"
subtitle = "Loop"
tag = "FILM"

[source]
type = "path"
value = "/Volumes/share/mars_films/2025/6_MILLION_DOLLAR_DUCK/EXPORTS/6_MILLION_DOLLAR_DUCK_1x1.mp4"
