id = "m-67e357c7-2aba-485d-bc03-fb3e81f36ba1-b79fb58959"
title = "67E357C7 2ABA 485D BC03 FB3E81F36BA1"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/67E357C7-2ABA-485D-BC03-FB3E81F36BA1.jpg"
cache = true
