id = "m-69f77b38-f060-49bf-a7cd-6f70f1b244fc-342dbcf15a"
title = "69F77B38 F060 49BF A7CD 6F70F1B244FC"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/69F77B38-F060-49BF-A7CD-6F70F1B244FC.jpg"
cache = true
