id = "m-6acc6207-4a05-4a2b-95bf-fe4c9f715da3-65f815bf48"
title = "6ACC6207 4A05 4A2B 95BF FE4C9F715DA3"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/6ACC6207-4A05-4A2B-95BF-FE4C9F715DA3.jpg"
cache = true
