id = "m-736b77d7-bdf2-49d9-a171-98cfa9daebe6-dc9db719b0"
title = "736B77D7 BDF2 49D9 A171 98CFA9DAEBE6"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/736B77D7-BDF2-49D9-A171-98CFA9DAEBE6.jpg"
cache = true
