id = "m-7d42edf7-8f37-4e0a-bcf5-c86a7bfd529a-36ae5ed28e"
title = "7D42EDF7 8F37 4E0A BCF5 C86A7BFD529A"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/7D42EDF7-8F37-4E0A-BCF5-C86A7BFD529A.jpg"
cache = true
