id = "m-7e30fe0e-3bc6-4411-9ce1-1f1d236b458e-3fdb8df1f1"
title = "7E30FE0E 3BC6 4411 9CE1 1F1D236B458E"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/7E30FE0E-3BC6-4411-9CE1-1F1D236B458E.jpg"
cache = true
