id = "m-876e9601-a179-454e-af68-c3d10abcff6e-c9d02fcf9b"
title = "876E9601 A179 454E AF68 C3D10ABCFF6E"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/876E9601-A179-454E-AF68-C3D10ABCFF6E.jpg"
cache = true
