id = "m-917c512d-596e-41a1-b0ed-b13fcc02d1cc-5bc6ccc678"
title = "917C512D 596E 41A1 B0ED B13FCC02D1CC"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/917C512D-596E-41A1-B0ED-B13FCC02D1CC.jpg"
cache = true
