id = "m-981b9e86-32bc-4d92-8930-9e9bc7be6a3b-aaa624499b"
title = "981B9E86 32BC 4D92 8930 9E9BC7BE6A3B"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/981B9E86-32BC-4D92-8930-9E9BC7BE6A3B.jpg"
cache = true
