id = "m-9e2f62f0-070b-41e3-882f-affebd9d581f-5f5c91f746"
title = "9E2F62F0 070B 41E3 882F AFFEBD9D581F"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/9E2F62F0-070B-41E3-882F-AFFEBD9D581F.jpg"
cache = true
