id = "m-a24ef8b0-8696-4f2c-a2f1-1219ced8e855-dd7d9b4647"
title = "A24EF8B0 8696 4F2C A2F1 1219CED8E855"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/A24EF8B0-8696-4F2C-A2F1-1219CED8E855.jpg"
cache = true
