id = "m-ancestresses-series-nature-of-movement-avag8hq-fic-4ed36213b9"
title = "Ancestresses series & Nature of Movement [avAG8Hq FIc]"
tag = "CHEBEL"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/chebel/Ancestresses series & Nature of Movement [avAG8Hq-FIc].mov"
cache = true
