id = "m-ayane-screen-test-61c2f7f01b"
title = "Ayane Screen Test"
tag = "EARL"
artist = "Earl"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/earl/Ayane Screen Test.mov"
cache = true
