id = "m-benjamin-franklin-hip-wizzard-dinosaur-in-background-on-mars-379172-0175d9cde6"
title = "benjamin franklin  hip wizzard dinosaur in background on mars 379172"
tag = "ZAYNE"
artist = "Zayne"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/zayne/benjamin franklin  hip wizzard dinosaur in background on mars 379172.png"
cache = true
