id = "m-bourbon-screen-test-aa49cf63b4"
title = "Bourbon Screen Test"
tag = "EARL"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/earl/Bourbon Screen Test.mov"
cache = true
