id = "m-c4bcf35a-ab71-4e57-8de5-9c0ec6b2508a-5c4524a043"
title = "C4BCF35A AB71 4E57 8DE5 9C0EC6B2508A"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/C4BCF35A-AB71-4E57-8DE5-9C0EC6B2508A.jpg"
cache = true
