id = "m-drumdrops-screen-test-e0cbe3555d"
title = "Drumdrops Screen Test"
tag = "EARL"
artist = "Earl"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/earl/Drumdrops Screen Test.mov"
cache = true
