id = "m-drawing-klerb-excerpt-f6e285771d"
title = "Drawing Klerb excerpt"
tag = "RIA"
artist = "Ria"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/ria/Drawing Klerb excerpt.mp4"
cache = true
