id = "m-e5a1a471-094c-42e0-95ca-caee3b4a97d8-d8f3bdb527"
title = "E5A1A471 094C 42E0 95CA CAEE3B4A97D8"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/E5A1A471-094C-42E0-95CA-CAEE3B4A97D8.jpg"
cache = true
