id = "m-early-visions-ac7tkelkfl8-83391fe30c"
title = "EARLY VISIONS [AC7tKelKfL8]"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/chebel/EARLY VISIONS [AC7tKelKfL8].mov"
cache = true
