id = "m-eden-66d23a86479cd41e902bf212"
title = "fireflies in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/f9e0cb288fe433d982e7c0c2224648b70da705b86bf6dccfdb7ffc509fa96722.jpg"
cache = true
