id = "m-eden-66461c121f76de1d686139e6"
title = "starry night, empty forest"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/1bdfaa05ba9a424c1b22d43684468e4fb319c1794b8658acd0e937366780567a.jpg"
cache = true
