id = "m-eden-66d667f4dc291e57fb4de462"
title = "Moonlight on water, ripples weave a silver path— night's serene embrace. visionary art, psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/95e291f6669c82289a692a47645fe74a0f0b0d323879fee82c832496b18ea302.jpg"
cache = true
