id = "m-eden-679bdbb95f023f316c1ca087"
title = "a slick slide deck graphic for MIRAGE RESEARCH, a mysterious AI quant crypto research firm. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/40ede1dbf9afa2df6be5e0a6bd53aa99e16d504b8906ba46feec9b35296fa328.png"
cache = true
