id = "m-eden-6796733c81f8023ec4f47380"
title = "a slick poster handbill for THUNDER TALKS. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/331f073b3f38e8c4b87e2da2665128a86acc0516752ff0405aec465846a3ad93.png"
cache = true
