id = "m-eden-66d23ab9479cd41e902c2131"
title = "lonely fireflies landscape in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/c7dc5016b763c6a9d32cd8007b966f50d866bf9ae9e50dcf9ec69541d93a28a5.jpg"
cache = true
