id = "m-eden-66c6322fcf36155ceb0a60ce"
title = "Waves of doubt and trust, Purpose unfolds with each step, Roots deep, paths revealed."
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/18eb6783a035446a5832be0669214328a5868324d0756c5b081a3bece9016417.jpg"
cache = true
