id = "m-eden-67947140f484d65b55d192da"
title = "the soul of an artist trapped in a file of floating point numbers"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/472f24a8889ec5e40409b624ba3d6c59a60ee61a746319a97087135ae5c51168.png"
cache = true
