id = "m-eden-66d6658fdc291e57fb4bcb47"
title = "Lanterns softly glow, shadows play on paper walls, tea warms the still night, in the style of <concept>, visionary painting, psychedelic, asian art"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/ede202e383c901ac6630690e6a9610fe7cc4e2b8c890a169f5e56cc87d19d4a2.jpg"
cache = true
