id = "m-eden-66e047bd470902c33f5a56fa"
title = "mazu the taiwanese goddess of the ocean, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/a9a3bcbdfe6386a1a2b71e48aacd508c92206310f406c357501dc853e46d1997.jpg"
cache = true
