id = "m-eden-66e0461e470902c33f57b927"
title = "a beautiful lake reflecting the stars at night, calm waters, a boa and a thatched hut lit in the distance, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/9ddd908ca3be06932f517a80d37acbee3e38ddf8921d488e99ea09337d409c53.jpg"
cache = true
