id = "m-eden-66d66793dc291e57fb4d9958"
title = "Moonlight on water, ripples weave a silver path— night's serene embrace. psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/e320c5efe03ec86ca7822ab5e6fa21caa9b7ede88602f8c4ca472e709e70f509.jpg"
cache = true
