id = "m-eden-66e048f9470902c33f5cd01b"
title = "close up of a water fountain, a bucket and a laddle, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/dc392f86c25f04d20b434062ae88d0ed34f5a661977f8fc46ca524528947445b.jpg"
cache = true
