id = "m-eden-66d665b4dc291e57fb4be4a3"
title = "Lanterns softly glow, shadows play on paper walls, tea warms the still night, in the style of <concept>, visionary painting, psychedelic, asian art"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/dd7df3de94b725ddab2167d573ef958bbbcb9fe8f805c0bcdf42f34c19f64207.jpg"
cache = true
