id = "m-eden-67ccc1c7e7712a0d8bce3882"
title = "this is a tbd side task"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/c3072fe424f1776463570ccf4cbb2f1e6f97e1730a53236f91c6fe73fc3255a9.png"
cache = true
