id = "m-eden-6796745c388bc563f6038234"
title = "a slick poster handbill for TRINKET TAROT, a mystical tarot reading experience in the desert. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/448bbafffe44546b6c6abd1b2a6abd525e0ecd799482d9f854000dfc37d501df.png"
cache = true
