id = "m-eden-66e047d9470902c33f5a898f"
title = "mazu the taiwanese goddess of the ocean, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/1abbc66bd5c3feee5d050a017ce3256df8335ed769fdbf8120079b830d7e61cd.jpg"
cache = true
