id = "m-eden-67cbde4f867fc6d4af22ea76"
title = "this is a tbd side task"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/fc0d106f0db45fdd9e8ee140f7758ad4f0ea2eec4d30c8b5d763703c4d57aac1.png"
cache = true
