id = "m-eden-66d23aa9479cd41e902c0b26"
title = "lonely fireflies landscape in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/bd89cc64d5e0934ea1dc4584c12657956e8bf94d80d5759ea4ff897aeffb53f4.jpg"
cache = true
