id = "m-eden-66d665cfdc291e57fb4c0fee"
title = "Lanterns softly glow, shadows play on paper walls, tea warms the still night, in the style of <concept>, visionary painting, psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/e3d3fb302278f7c73d34a3a94faefa538435a6d9841e0648a65055380fa52496.jpg"
cache = true
