id = "m-eden-66d66916dc291e57fb4f44a7"
title = "A tranquil pond rests, lotus blooms float like bright stars— reflections shimmer. psychedelic, visionary painting, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/14a66895fccd3db99cd23e7a96d36101dcc59aae3ab2e1175d64b6757ac6baeb.jpg"
cache = true
