id = "m-eden-67947fa3a53fe37b580ab03d"
title = "an extremely rich mechanical duck at a cryptocurrency conference, candle chart in the background"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/579111342f0c50bcc339f0f5b6c7df78686620440a3d26b4b65e4eeca687427f.png"
cache = true
