id = "m-eden-66458ce21f76de1d6829f0cc"
title = "a mountain landscape and a single tree being hit by a lightning bolt, thunderstorm"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/19b28f33d293de0bcab4ba12c880dd5c8ed7f37b71cf5c7349205f1a16ae66d5.jpg"
cache = true
