id = "m-eden-67dafa39dbe6528fa17b34ac"
title = "giant heads, huge sculptures of a head in a field by the moonlight, full moon in the sky, stars, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/1afffdafe265b1f4990818d8ae4a0c1904a5d6ef6c5ad0bad4fe29befbc5ad6d.png"
cache = true
