id = "m-eden-66e0497a470902c33f5d56f8"
title = "close up of a water fountain, a bucket and a laddle, asian art"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/0eccd1ff41b52c563af82ff3f90ef4c9637978e29fdb927f978e54bc904c4505.jpg"
cache = true
