id = "m-eden-66d23ad9479cd41e902c5037"
title = "lonely fireflies landscape in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/8b011734f6524a6307f7c7a0b40024f43ee6550cecb91504da779a465b737a9d.jpg"
cache = true
