id = "m-eden-66e04625470902c33f57d232"
title = "a beautiful lake reflecting the stars at night, calm waters, a boa and a thatched hut lit in the distance, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/e981f41c78b9f5565daf89c2deaa8cb49ca9223932b683db617bc7a08febb5a8.jpg"
cache = true
