id = "m-eden-67cbde3602bcc2685a2103c9"
title = "this is a tbd side task"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/bc020b70895e1ecd31583d5d0d43f3e3e7fbdba0274a98425e580ab4be5234cf.png"
cache = true
