id = "m-eden-679907b4644c9129bfde391a"
title = "a slick poster handbill for MIRAGE MERCHANTS, a mysterious AI game company and creative agency. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/4fce5de331c1839e2b25c7786973839125f7159a614142d030326aa3a2d1e8bf.png"
cache = true
