id = "m-eden-698e39ecb02116113cd3d0f7"
title = "hologram spirit: composition made up of glowing binary code, symbolizing the merging of human emotion and technology, incredible digital art, cyberpunk, neon colors, glitch effects, 3D octane render, HD"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/afeed3c7a6301753fa97250936437aa1ccc8547364c04cc4da40effd29c6cf31.png"
cache = true
