id = "m-eden-66d668b6dc291e57fb4ecff2"
title = "A tranquil pond rests, lotus blooms float like bright stars— reflections shimmer. psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/403ada660022ccfa54735af983588b5b765a82521994ce85c037dd163aec39f6.jpg"
cache = true
