id = "m-eden-66461cf51f76de1d6861ecd0"
title = "eyes pattern, many eyes, eye in the sky, eyes as stars"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/73db9cf669e76c024cb9b1ca5ee07c861f8b5a38c2eac00ba974bf7f5adf646d.jpg"
cache = true
