id = "m-eden-679677a879a2ee8099a06f2a"
title = "a slick poster handbill for TRINKET TAROT, a mystical tarot reading experience in the desert. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/8e3b1069455c66e689b063b827ee16965ea31975d1beb220b48d04286aa0ad3f.png"
cache = true
