id = "m-eden-66e04ca6470902c33f61a28c"
title = "a chinese dragon in the sky"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/be20723901efc777bfa43334fa561539fb4f7c8818bd3e6d43770cc9187a2100.jpg"
cache = true
