id = "m-eden-66d23a2f479cd41e902bb3b3"
title = "fireflies in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/37c1e13c1ddf467b86fab1afad57a7bfc1531c16fb986b8cb1092d116f07f97d.jpg"
cache = true
