id = "m-eden-66d67276dc291e57fb54e730"
title = "Gentle autumn breeze, leaves dance upon the still pond, nature's soft whisper, visionary painting, psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/f5a7341b979c4834d66e282bdf30f1b19ec69bd7fedfb50c2ff70e609e695f2f.jpg"
cache = true
