id = "m-eden-creation-aliciasadventuresreference-image-1-cosmic-butterfly-garden-composition-prese698102805f5a3983a319816b-f4ec1bf278"
title = "Eden creation aliciasadventuresReference Image 1 cosmic butterfly garden composition prese698102805f5a3983a319816b"
tag = "ALICIA"
artist = "Alicia"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/alicia/Eden_creation_aliciasadventuresReference-Image-1-cosmic-butterfly-garden-composition-prese698102805f5a3983a319816b.mp4"
cache = true
