id = "m-eden-66c631e0cf36155ceb0a437e"
title = "Waves of doubt and trust, Purpose unfolds with each step, Roots deep, paths revealed."
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/402b7f91deea6f88a2777a563f32786cb8e8ea0826ee4121a108eb121012de50.jpg"
cache = true
