id = "m-eden-65ccf12fb6124cd312101de4"
title = "oil paint, brush strokes, mixed media, woman, soft pastel sunset colors"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/856d8d488d22b41a4f866030637edf3b45eabddd830b0bf12978f750a5c19af4.jpg"
cache = true
