id = "m-eden-66461daf4a40c7cdc3c44e5e"
title = "buto dancer dressed all in white"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/e5fd274528b08c996371f1738761423299407bc0a538392e590c8e6ba181342c.jpg"
cache = true
