id = "m-eden-66e04b42470902c33f5e8a3b"
title = "tea ceremony, asian art"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/f2422b93472d6c37bdacb2e13f7afc91e811f61fbada5fd51692463ffd10448a.jpg"
cache = true
