id = "m-eden-66d6663adc291e57fb4c595e"
title = "steam rises gently, fragrant leaves unfurl and dance, time slows, peace descends, in the style of <concept>, visionary painting, psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/d1f9d5f851435338a949f992ef0e47e549aa1c6345476eae216d5b487053cd6b.jpg"
cache = true
