id = "m-eden-66df762781c18004b759b297"
title = "Waves of doubt and trust, Purpose unfolds with each step, Roots deep, paths revealed, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/7dfdbed8c8e93faf1e5a941321a61e5935567ce82ec93d64734a0d2a98495f12.jpg"
cache = true
