id = "m-eden-67947be0a53fe37b580ab025"
title = "a ghost town in the desert, dilapidated, derelict, makeshift, scrapwork"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/822522f5998152029abf78ee0dc76edb525dc368a299cbd13dfae95a2d63707b.png"
cache = true
