id = "m-eden-66e0465e470902c33f581752"
title = "a beautiful lake reflecting the stars at night, calm waters, a boat and a thatched hut lit in the distance, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/ad6cbc9f210e07d2ec1ee9fa59c1aa8475786597287753f49896cfd49b4f3113.jpg"
cache = true
