id = "m-eden-67e32f28b55cd39393a0e0a5"
title = "A verdant, lush, green, hotel atrium with a pool"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/ea462b0ddb94470a9f200b0c8851253827865744b4b3ddcfec34231d06bd9e2e.png"
cache = true
