id = "m-eden-698e33d95ccc27be2922f831"
title = "fireflies in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/c011b041f55340fc76a850eff6bcae42d88e2c425e6d2815b512edc6b7bdb272.png"
cache = true
