id = "m-eden-66461dc84a40c7cdc3c478fc"
title = "sichuan opera dancer"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/8604a7001ab8cdf72ca9505f40bda7a2b5ec7a8f47a1e5d702d859294564ab53.jpg"
cache = true
