id = "m-eden-679482e0a53fe37b580ab052"
title = "an extremely rich mechanical duck trading cryptocurrency on his phone, gate.io binance flashy investor slide deck graphics"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/caae1b43af0cbffd7baa5036e39ba9cf4f626fee2204e61ef0bb4dddd8a2ea2e.png"
cache = true
