id = "m-eden-698e341c5ccc27be2922f835"
title = "fireflies in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/64593abe4edebaa1e40a5245ad765a4b4bc2a3f9217b4f7078489c9b92dead6f.png"
cache = true
