id = "m-eden-66e0470b470902c33f5913d9"
title = "the waves in the ocean breaking on the shore, sea of stars, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/e1a67edcd4f3b2581120c1a85c0062ac766f890c1733bf3a2e1dc1d96a476436.jpg"
cache = true
