id = "m-eden-66d665f9dc291e57fb4c2964"
title = "Lanterns softly glow, shadows play on paper walls, tea warms the still night, in the style of <concept>, visionary painting, psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/6de2c0776a9fded40e0b27d958d0b80e8174600b16cbe3f8d0a77ea7692fab23.jpg"
cache = true
