id = "m-eden-67967cf8d297c39e0fa75e1c"
title = "a slick poster handbill for TRINKET TAROT, a mystical tarot reading experience. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/963a8a5bf3adb649d15f6c25f3e29da6a3eb0db69e3dd4b9f8a66713aa8d8bb8.png"
cache = true
