id = "m-eden-66e0463e470902c33f57e84d"
title = "a beautiful lake reflecting the stars at night, calm waters, a boat and a thatched hut lit in the distance, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/d4fa0b3bd9e2ccc48b2fe0bfdc2cf1cb0a2f9d851635e130d3a6d32ba09f8fa7.jpg"
cache = true
