id = "m-eden-66e04e94470902c33f66029d"
title = "Plum Blossom"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/e0d2a97cd9581e86ace468465147438835f329e5ddb02817c6dc941ab5ff66ea.jpg"
cache = true
