id = "m-eden-66e04851470902c33f5bb944"
title = "mist, fog, misty mountains, mysterious foggy hills, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/0046e9c76adcc17a0c7315d7d59101b69ef35b0fa0fc5373a0de4adf1e249120.jpg"
cache = true
