id = "m-eden-67947d33a2400dbdfe6fcbf9"
title = "a JRPG battle screen, epic battle, spellcasting,"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/35ee13de941e63466098eee8a1cb99c6db34baf39e0996b491faa39b7810cd3c.png"
cache = true
