id = "m-eden-67dafa4cdbe6528fa17b34ae"
title = "giant heads, huge sculptures of a head in a field by the moonlight, full moon in the sky, stars, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/5d47f53c18c577636440c20b3aadddace95afeff035a53d24e9d2272bfcb4d8f.png"
cache = true
