id = "m-eden-66d66dc1dc291e57fb512891"
title = "A winding stone path, black background, moss clings to ancient footsteps, mist weaves through the trees. visionary painting, psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/1741bd378a9c1482feec4ac8e9906192aa2253917bcff0d472871a7462327393.jpg"
cache = true
