id = "m-eden-66d23a5b479cd41e902bc3a1"
title = "fireflies in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/a38ff5e7f694b8cd29257df34db7ad320ca4d53670cf23b23d389953b0fada93.jpg"
cache = true
