id = "m-eden-66d23af9479cd41e902c9ab3"
title = "lonely fireflies landscape in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/7438986899115ad1c8d158153b47893c992830bed2d71efa60fbad3d6a837e28.jpg"
cache = true
