id = "m-eden-66d671e4dc291e57fb547c5f"
title = "a lettering in painted letters with the title \"CHEBEL\" in colorful paint painted by cuno amiet in black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/8a8470257343479824709e4d1fc91e452c78ede91e3c157029ceeecb677b9ed9.jpg"
cache = true
