id = "m-eden-679925d0882a459f5efddb06"
title = "a slick slide deck graphic for MIRAGE MERCHANTS, a mysterious AI game company and creative agency. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/f05db821b24ee76a5855592434f23f4ba9a3e8799bfa2cace9b32ad1be3cdf1e.png"
cache = true
