id = "m-eden-67967d0cd297c39e0fa75e1d"
title = "a slick poster handbill for TRINKET TAROT, a mystical tarot reading experience. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/2f18a06cee5aa97801eec9393760ec3b79fa59df86b008d83222a3344aa2ec4b.png"
cache = true
