id = "m-eden-67967d36d297c39e0fa75e1f"
title = "a slick poster handbill for TRINKET TAROT, a mystical tarot reading experience. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/d001bffe7a0a15d692a70e0259a696eca10dff4aa7580a26eeb7db10546f28bd.png"
cache = true
