id = "m-eden-6799078b644c9129bfde3918"
title = "a slick poster handbill for MIRAGE MERCHANTS, a mysterious AI game company and creative agency. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/c38734c4077416ba526422fd5e70e4c000c67d4147d84424ad8875daad651d1f.png"
cache = true
