id = "m-eden-6796735381f8023ec4f47381"
title = "a slick poster handbill for THUNDER TALKS. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/b177bfa96ad5c99e3c5f5aabe8197c7c6d8b9ff569ff336d6bd3c7a85820b5a7.png"
cache = true
