id = "m-eden-679677e679a2ee8099a06f2d"
title = "a slick poster handbill for TRINKET TAROT, a mystical tarot reading experience in the desert. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/8c9df950e4851d334c47ff822c39d364c936e45b5bef4c19ee988f86ec3f976e.png"
cache = true
