id = "m-eden-664619991f76de1d685f18df"
title = "a volcano erupting at night"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/cc1549278b88d09c321f3206e0b0d1da3d43572dbd40e377e124c5fa6f11b61a.jpg"
cache = true
