id = "m-eden-65c95b10ca4d4960370badf6"
title = "oil paint, friends, community, love, soft colors"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/5a93ed9297b62d50a7f79eaa3a2c1c7b1d4813517fc0b378f94fe4ab0e589bf2.jpg"
cache = true
