id = "m-eden-66e04651470902c33f580159"
title = "a beautiful lake reflecting the stars at night, calm waters, a boat and a thatched hut lit in the distance, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/520d36bf3e64e99d81f772c517ba07d5fb3e07425958d50fac21e91bcd053f12.jpg"
cache = true
