id = "m-eden-65ccef9fb6124cd3120da632"
title = "oil paint, brush strokes, mixed media, women talking, soft pastel sunset colors"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/e351550625f78134453efc45ac5942d438bea82d78ef8b4ed26a31a2fc0ae766.jpg"
cache = true
