id = "m-eden-66458d601f76de1d682a8ea2"
title = "women bathing in a waterfall"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/75e233b9ecb72dca75c7b2bfb5d7e05a63d9c893a134f6d282f1ae752fd634dd.jpg"
cache = true
