id = "m-eden-66d668c4dc291e57fb4ed658"
title = "A tranquil pond rests, lotus blooms float like bright stars— reflections shimmer. psychedelic, visionary painting, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/bece6688fd96405a01aa0c731e828e6620988777afb08bdd64f7bb986d3062dd.jpg"
cache = true
