id = "m-eden-66461d354a40c7cdc3c3b7a8"
title = "eyes pattern, many eyes, eye in the sky, eyes as stars"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/60f456b96eaaf75df4dd9dae56616f1a6de17a1b940f4346d92aee91d4dbad39.jpg"
cache = true
