id = "m-eden-66d66a5fdc291e57fb503d27"
title = "A winding stone path, black background, moss clings to ancient footsteps, mist weaves through the trees. visionary painting, psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/90a2fd7aca35151b0065615749fd66489f1700e04a7f745e23fc24272a1d4e19.jpg"
cache = true
