id = "m-eden-66d6692cdc291e57fb4f5fab"
title = "A tranquil pond rests, lotus blooms float like bright stars— reflections shimmer. asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/6cf9e619d4343730300ada4ca12066d144f29278d0fc7a81561db56fa90d7627.jpg"
cache = true
