id = "m-eden-65c95ba5ca4d4960370c3a4f"
title = "oil paint, friends, community, love, soft colors"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/498aa0cb8f02679ad5e4cca8ef137dc2507608a3149647989dfeb917abb63b4b.jpg"
cache = true
