id = "m-eden-66461be81f76de1d68611d94"
title = "starry night, empty forest"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/cc5c3a8b2089290b7f17e32ba84b178d5e1e00927e4f0a670355270e38137369.jpg"
cache = true
