id = "m-eden-66d238b6479cd41e902b6d7d"
title = "fireflies in a dark background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/833664e630092f02d83ce71d9165da9dd9ea2e89127366300b6f0dde6ca270bd.jpg"
cache = true
