id = "m-eden-66e04617470902c33f57afae"
title = "a beautiful lake reflecting the stars at night, calm waters, a boa and a thatched hut lit in the distance, asian art, painting, chinese, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/6cbaf02c6e4ffd0074887ad88501c0036b95990e57a30b3d07b28932971bb8a7.jpg"
cache = true
