id = "m-eden-66d66ea8dc291e57fb518597"
title = "A winding stone path, black background, moss clings to ancient footsteps, mist weaves through the trees. visionary painting, psychedelic, asian art, black background"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/13095c54c4f442fe462bfc7aba9a93d4e555b8e95c665cded8faaa6eb6b6ff43.jpg"
cache = true
