id = "m-eden-65c95ba5ca4d4960370c3a4e"
title = "oil paint, friends, community, love, soft colors"
kind = "image"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/ec44fbe1e90aad992592bded64df9dc67389481b15986a8bf3c84d985f3fa1fa.jpg"
cache = true
