id = "m-eden-679483c1c4a706544935a759"
title = "an extremely rich mechanical duck trading cryptocurrency, sega genesis box art, retro, mellow soft colors, centered, pastel lighting"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/ea072cc2856f78f7207a9e51af6f574f80254695163a069aaeb0400dad4e52f9.png"
cache = true
