id = "m-eden-679677d179a2ee8099a06f2c"
title = "a slick poster handbill for TRINKET TAROT, a mystical tarot reading experience in the desert. beautiful typography, low-key color composition"
kind = "image"
tag = "JMILL"
artist = "jmill"

[source]
type = "url"
value = "https://d14i3advvh2bvd.cloudfront.net/ef293b6f23db38a960096edb7776d8255ae1f6b9598bc6c3b49b946610a1d41e.png"
cache = true
