id = "m-environment-prefinal-recolor-03-8db90d8b84"
title = "environment prefinal recolor 03"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/environment-prefinal-recolor-03.mp4"
cache = true
