id = "m-f06e47dd-7b91-4bba-91f4-2ebbd308649c-411127f8f9"
title = "F06E47DD 7B91 4BBA 91F4 2EBBD308649C"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/F06E47DD-7B91-4BBA-91F4-2EBBD308649C.jpg"
cache = true
