id = "m-f3a10ec9-665f-4d68-b6e4-f0d71987ee68-d1b2a517cf"
title = "F3A10EC9 665F 4D68 B6E4 F0D71987EE68"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/F3A10EC9-665F-4D68-B6E4-F0D71987EE68.jpg"
cache = true
