id = "m-f4f0d1b1-ee17-479c-ad7f-035f34afe9c5-b17cf8c849"
title = "F4F0D1B1 EE17 479C AD7F 035F34AFE9C5"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/F4F0D1B1-EE17-479C-AD7F-035F34AFE9C5.jpg"
cache = true
