id = "m-firefly-gemini-flash-primary-prompt-retro-cartoon-80s-action-movie-poster-style-steve-j-savage-vs-ali-504124-67b6c4abec"
title = "Firefly Gemini Flash Primary Prompt Retro cartoon 80s action movie poster style,  Steve J. Savage Vs. Ali 504124"
tag = "ZAYNE"
artist = "Zayne"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/zayne/Firefly_Gemini Flash_Primary Prompt-_Retro cartoon 80s action movie poster style, -Steve J. Savage Vs. Ali 504124.png"
cache = true
