id = "m-firefly-gemini-flash-luna-robot-image-generation-prompt-a-friendly-bipedal-robot-companion-inspired-by-a-504124-d695f6e4ed"
title = "Firefly Gemini Flash Luna Robot   Image Generation Prompt A friendly bipedal robot companion inspired by a 504124"
tag = "ZAYNE"
artist = "Zayne"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/zayne/Firefly_Gemini Flash_Luna Robot - Image Generation Prompt_A friendly bipedal robot companion inspired by a 504124.png"
cache = true
