id = "m-full-band-screen-test-98065ba4b4"
title = "Full Band Screen Test"
tag = "EARL"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/earl/Full Band Screen Test.mov"
cache = true
