id = "m-how-to-make-a-fly-90s-website-a-geocities-tribute-stryve-18a326d5ee"
title = "How to make a fly 90s website A GeoCities tribute  Stryve"
tag = "MIDTERMS"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/placeholder/How to make a fly 90s website A GeoCities tribute  Stryve.gif"
cache = true
