id = "m-lesha-fedorov-grace-42383173ba"
title = "Lesha Fedorov   Grace"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/Lesha Fedorov - Grace.png"
cache = true
