id = "m-lunarobotraccoonconcept-1-fcb3ea0865"
title = "LunaRobotRaccoonConcept 1"
tag = "ZAYNE"
artist = "Zayne"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/zayne/LunaRobotRaccoonConcept_1.jpg"
cache = true
