id = "m-mars-midterm-19-ce2cf663af"
title = "Mars Midterm 19"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/Mars Midterm 19.png"
cache = true
