id = "m-mars-midterm-15-e993f12ae8"
title = "Mars Midterm 15"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/Mars Midterm 15.png"
cache = true
