id = "m-mars-midterm-1-7016708adf"
title = "Mars midterm 1"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/Mars midterm 1.png"
cache = true
