id = "m-make-my-art-more-trippy-5fa33825ca"
title = "Make my art more trippy"
tag = "ALICIA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/alicia/Make_my_art_more_trippy.png"
cache = true
