id = "m-mars-midterm-14-55488539da"
title = "Mars Midterm 14"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/Mars Midterm 14.png"
cache = true
