id = "m-mars-midterm-25-c224333561"
title = "mars midterm 25"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/mars midterm 25.png"
cache = true
