id = "m-mars-midterm-5-810c4b68f0"
title = "Mars midterm 5"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/Mars midterm 5.png"
cache = true
