id = "m-mars-midterm-23-4700c1b79e"
title = "mars midterm 23"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/mars midterm 23.png"
cache = true
