id = "m-mars-midterm-27-f6d13a374a"
title = "mars midterm 27"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/mars midterm 27.png"
cache = true
