id = "m-mars-midterm-2-19c9f36c8a"
title = "Mars midterm 2"
tag = "CO-LAB"
artist = "Community Lab"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/co-lab/Mars midterm 2.png"
cache = true
