id = "m-photo-2021-06-01-08-24-24-dd48439ff0"
title = "photo 2021 06 01 08 24 24"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/photo_2021-06-01_08-24-24.png"
cache = true
