id = "m-quantum-poetry-by-kza-2-f317e21a13"
title = "Quantum Poetry by KzA (2)"
tag = "KAMAU"
artist = "KzA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/kamau/Quantum Poetry by KzA (2).mp4"
cache = true
