id = "m-scan-20220408-191956-copy-13dbe74bad"
title = "Scan 20220408 191956   Copy"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/Scan_20220408_191956 - Copy.png"
cache = true
