id = "m-scan-20220407-164917-2-97d232749d"
title = "Scan 20220407 164917 2"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/Scan_20220407_164917_2.png"
cache = true
