id = "m-scan-20220408-190634-2-dd72d1d58a"
title = "Scan 20220408 190634 2"
tag = "LYOSHA"
artist = "Lyosha"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/Scan_20220408_190634_2.png"
cache = true
