id = "m-star-motion-graphics-b-roll-test-1829b26fa0"
title = "Star motion graphics b roll test"
tag = "EARL"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/earl/Star motion graphics b-roll test.mov"
cache = true
