id = "m-t-mort-screen-test-aa40df2c6a"
title = "T Mort Screen Test"
tag = "EARL"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/earl/T Mort Screen Test.mov"
cache = true
