id = "m-the-wedding-of-the-sun-and-the-moon-e-pkhgjh0pa-eeeff1a4e1"
title = "The Wedding of the Sun and the Moon [E PkHGJH0PA]"
tag = "CHEBEL"
artist = "Chebel"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/chebel/The Wedding of the Sun and the Moon [E_PkHGJH0PA].mov"
cache = true
