id = "m-untitled-artwork-c5b6f08b97"
title = "Untitled Artwork"
tag = "LYOSHA"

[source]
type = "path"
value = "/Volumes/share/chiba-cable/assets/mc26/midterms/lyosha/Untitled_Artwork.gif"
cache = true
